# -*- coding: utf-8 -*-
"""Affine Cipher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g31aT8DgUqMTjOW2x8sOLiwKWH6xBmDH
"""

def gcd(a, b):
    while b != 0:
        a, b = b, a % b
    return a

def mod_inverse(a, m):
    for x in range(1, m):
        if (a * x) % m == 1:
            return x
    raise ValueError("Modular inverse does not exist")

def affine_encrypt(text, a, b):
    if gcd(a, 26) != 1:
        raise ValueError("Key 'a' must be coprime with 26")

    encrypted_text = ""
    for char in text:
        if char.isalpha():
            if char.isupper():
                encrypted_text += chr(((a * (ord(char) - 65) + b) % 26) + 65)
            else:
                encrypted_text += chr(((a * (ord(char) - 97) + b) % 26) + 97)
        else:
            encrypted_text += char

    return encrypted_text

def affine_decrypt(ciphertext, a, b):
    if gcd(a, 26) != 1:
        raise ValueError("Key 'a' must be coprime with 26")

    a_inv = mod_inverse(a, 26)

    decrypted_text = ""
    for char in ciphertext:
        if char.isalpha():
            if char.isupper():
                decrypted_text += chr(((a_inv * (ord(char) - 65 - b)) % 26) + 65)
            else:
                decrypted_text += chr(((a_inv * (ord(char) - 97 - b)) % 26) + 97)
        else:
            decrypted_text += char

    return decrypted_text

if __name__ == "__main__":
    print("Affine Cipher Program")

    choice = input("Pilih operasi (enkripsi/dekripsi): ").strip().lower()
    text = input("Masukkan teks: ").strip()
    a = int(input("Masukkan kunci a (prima dengan 26): "))
    b = int(input("Masukkan kunci b: "))

    try:
        if choice == "enkripsi":
            result = affine_encrypt(text, a, b)
            print("Hasil enkripsi:", result)
        elif choice == "dekripsi":
            result = affine_decrypt(text, a, b)
            print("Hasil dekripsi:", result)
        else:
            print("Operasi tidak valid.")
    except ValueError as e:
        print("Error:", e)